/* ============================================================
   SQL 개념 정리
   ============================================================

   [기본 조회]
   - SELECT ... FROM ... WHERE         기본 조회 + 조건 필터
   - ORDER BY col ASC|DESC             정렬 (기본 ASC)
   - LIMIT N                           출력 개수 제한

   [집계 함수]
   - COUNT(*), COUNT(DISTINCT col)     개수 (중복 제거 가능)
   - AVG(col), SUM(col)               평균, 합계
   - MAX(col), MIN(col)               최대, 최소
   - ROUND(값, 자릿수)                 반올림

   [그룹화]
   - GROUP BY col                      동일 값끼리 묶어 집계
     → 집계 함수 외 모든 SELECT 컬럼은 GROUP BY에 포함해야 함
   - HAVING 조건                       그룹에 대한 필터 (WHERE는 행 필터)

   [조건 / NULL 처리]
   - BETWEEN a AND b                   범위 조건
   - LIKE '패턴%'                      문자열 패턴 매칭
   - IN (값1, 값2, ...)                목록 포함 여부
   - IS NULL / IS NOT NULL             NULL 비교 (= NULL은 안 됨!)
   - IFNULL(col, 대체값)               NULL이면 대체값 출력
   - CASE WHEN 조건 THEN 값 ... END    조건 분기

   [JOIN]
   - JOIN ... ON 조건                  양쪽 다 매칭되는 행만
   - LEFT JOIN ... ON 조건             왼쪽 테이블 전체 유지, 매칭 안 되면 NULL

   [서브쿼리]
   - WHERE col = (SELECT ...)          스칼라 서브쿼리
   - WHERE (col1, col2) IN (SELECT ...)  다중 컬럼 서브쿼리
   - WHERE NOT EXISTS (SELECT ...)     존재하지 않는 행 필터

   [합집합]
   - UNION ALL                         중복 포함 합치기 (중복 제거는 UNION)
   - NULL AS col                       없는 컬럼을 NULL로 채워 맞추기

   [윈도우 함수]
   - 함수() OVER (PARTITION BY col)    그룹별 집계값을 새 컬럼으로 추가
     → GROUP BY와 달리 행이 사라지지 않음
   - PERCENT_RANK() OVER (ORDER BY col) 순위 백분율 (0~1)

   [재귀 CTE]
   - WITH RECURSIVE 이름 AS (          계층/트리 구조 순회
       초기 쿼리
       UNION ALL
       재귀 쿼리
     )

   [문자열 / 날짜]
   - CONCAT(값1, 값2, ...)             문자열 이어붙이기
   - DATE_FORMAT(날짜, '%Y-%m-%d')     날짜 포맷 변환
   - YEAR(날짜), MONTH(날짜)           연도/월 추출

   ============================================================ */


-- ============================================================
-- 예제 모음
-- ============================================================


-- [기본 조회 + ROUND + AVG]
SELECT ROUND(AVG(DAILY_FEE)) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE='SUV';


-- [ORDER BY 다중 정렬]
SELECT FLAVOR FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID;


-- [GROUP BY + HAVING: 중복 조합 필터]
SELECT USER_ID, PRODUCT_ID FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY USER_ID, PRODUCT_ID DESC;


-- [서브쿼리: 가장 작은/큰 값 찾기 - NOT EXISTS]
SELECT D1.NAME FROM ANIMAL_INS D1
WHERE NOT EXISTS (
    SELECT 1 FROM ANIMAL_INS D2
    WHERE D2.DATETIME < D1.DATETIME
);

-- [서브쿼리: 가장 작은/큰 값 찾기 - LIMIT]
SELECT NAME FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1;


-- [DATE_FORMAT + YEAR 필터]
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE YEAR(PUBLISHED_DATE)=2021 AND CATEGORY='인문'
ORDER BY PUBLISHED_DATE ASC;


-- [IFNULL: NULL 대체]
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE GEND_CD='W' AND AGE<=12
ORDER BY AGE DESC, PT_NAME ASC;


-- [JOIN ON]
SELECT F.FLAVOR FROM FIRST_HALF F
JOIN ICECREAM_INFO I ON F.FLAVOR=I.FLAVOR
WHERE F.TOTAL_ORDER>3000 AND I.INGREDIENT_TYPE='fruit_based'
ORDER BY F.TOTAL_ORDER DESC;


-- [LIKE: 문자열 패턴 검색]
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS FROM FOOD_FACTORY
WHERE ADDRESS LIKE '강원도%'
ORDER BY FACTORY_ID ASC;


-- [GROUP BY + JOIN + ROUND(AVG)]
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
       ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I
JOIN REST_REVIEW R ON I.REST_ID=R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;


-- [UNION ALL + NULL AS]
SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
       PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3

UNION ALL

SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE,
       PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;


-- [COUNT + BETWEEN: 특정 조건 개수]
SELECT COUNT(*) AS USERS FROM USER_INFO
WHERE YEAR(JOINED)=2021 AND AGE BETWEEN 20 AND 29;


-- [셀프 JOIN: 부모-자식 관계 탐색]
SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY FROM ITEM_INFO I
JOIN ITEM_TREE T ON T.ITEM_ID=I.ITEM_ID
JOIN ITEM_INFO P ON T.PARENT_ITEM_ID=P.ITEM_ID
WHERE P.RARITY='RARE'
ORDER BY I.ITEM_ID DESC;


-- [LIMIT: 상위 N개]
SELECT ID, LENGTH FROM FISH_INFO
ORDER BY LENGTH DESC, ID ASC
LIMIT 10;


-- [COUNT + IN: 특정 값 필터]
SELECT COUNT(*) AS FISH_COUNT FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE=FNI.FISH_TYPE
WHERE FNI.FISH_NAME IN ('BASS','SNAPPER');


-- [LEFT JOIN: NULL 포함 전체 유지]
SELECT P.ID, COUNT(C.ID) AS CHILD_COUNT FROM ECOLI_DATA P
LEFT JOIN ECOLI_DATA C ON P.ID=C.PARENT_ID
GROUP BY P.ID
ORDER BY P.ID ASC;


-- [CASE WHEN: 조건 분기]
SELECT ID,
    CASE
        WHEN SIZE_OF_COLONY<=100 THEN 'LOW'
        WHEN SIZE_OF_COLONY<=1000 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SIZE
FROM ECOLI_DATA
ORDER BY ID;


-- [윈도우 함수: PERCENT_RANK]
SELECT ID,
    CASE
        WHEN PR <= 0.25 THEN 'CRITICAL'
        WHEN PR <= 0.5  THEN 'HIGH'
        WHEN PR <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PR
    FROM ECOLI_DATA
) T
ORDER BY ID ASC;


-- [WITH RECURSIVE: 계층 구조 순회]
WITH RECURSIVE GEN AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN G ON E.PARENT_ID = G.ID
)
SELECT COUNT(*) AS COUNT, G.GENERATION
FROM GEN G
LEFT JOIN ECOLI_DATA C ON G.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION ASC;


-- [COUNT(DISTINCT): 중복 제거 개수]
SELECT COUNT(DISTINCT NAME) AS COUNT FROM ANIMAL_INS;


-- [서브쿼리: 최대/최소값 행 조회]
SELECT * FROM FOOD_PRODUCT
WHERE PRICE=(SELECT MAX(PRICE) FROM FOOD_PRODUCT);

-- [대안: ORDER BY + LIMIT]
SELECT * FROM FOOD_PRODUCT
ORDER BY PRICE DESC
LIMIT 1;


-- [다중 컬럼 서브쿼리: 그룹별 최대값 행]
SELECT F.ID, N.FISH_NAME, F.LENGTH FROM FISH_INFO F
JOIN FISH_NAME_INFO N ON F.FISH_TYPE=N.FISH_TYPE
WHERE (F.FISH_TYPE, F.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY F.ID ASC;


-- [CONCAT: 문자열 편집]
SELECT CONCAT(MAX(LENGTH), 'cm') AS MAX_LENGTH FROM FISH_INFO;


-- [윈도우 함수: PARTITION BY로 그룹별 집계 + 원본 유지]
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) OVER (
        PARTITION BY YEAR(DIFFERENTIATION_DATE)
    ) - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA
ORDER BY YEAR ASC, YEAR_DEV ASC;
